#!/bin/bash

root_dir="/c/cpp/solutions/"
solution_dir=${root_dir}$1"/"
project_dir=${solution_dir}"src/"
mkpjt_file=${project_dir}"mkpjt"

clear
AutoMake -s ${root_dir} $1

str="
#!/bin/bash \n
\n
clear \n
AutoMake.exe -p ${project_dir} \$1 \n
"

echo -e ${str} > ${mkpjt_file}

