#!/bin/bash

clear

mkpjt_context="
#!/bin/bash \n\n
clear \n\n
../../AutoMaker.o -p ./ \$1  \n\n
chmod a+x ./\$1/mk.mk \n\n
cd ./\$1  \n
vim \$1.h \n
"

./AutoMaker.o -s ./ $1

echo -e $mkpjt_context > ./$1/src/mkpjt
chmod a+x ./$1/src/mkpjt

cd ./$1/src


