#!/bin/bash

clear

g++ TNet.cc Address.cc \
-l	file \
-l	log  \
-l  pthread \
    test_TNet_func.cc  \
-o ../../bin/test_TNet_func.cc


chmod a+x ../../bin/test_TNet_func.cc 

../../bin/test_TNet_func.cc

